simple_robot:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100  
  
  # Position Controllers ---------------------------------------
  joint0_position_controller:
    type: position_controllers/JointPositionController
    joint: finger0_joint_0
    pid: {p: 100.0, i: 0.01, d: 10.0}
